var DataPhone=[
	[
		{
			img:'images/images1/hot22.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
		{
			img:'images/images1/hot2.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
		{
			img:'images/images1/hot22.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
		{
			img:'images/images1/hot2.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		}
	]

];
var DataGoods=[
	[
		{
			img:'images/images1/hot22.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
		{
			img:'images/images1/hot22.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
		{
			img:'images/images1/hot22.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
		{
			img:'images/images1/hot22.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
		{
			img:'images/images1/hot2.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
		{
			img:'images/images1/hot2.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
		{
			img:'images/images1/hot2.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
		{
			img:'images/images1/hot2.png',
			info:'畅呼吸智能空气净化器',
			desc:'购新品除空气净化器',
			price:'￥&nbsp2999.00',
			check:'查看详情',
			purchase:'加入购物车'
		},
	],

];
var DataNavPhone=[
	[
		{
			img:"images/images1/hot22.png",
			name:'坚果1',
			price:'2499元起'
		},
		{
			img:"images/images1/hot22.png",
			name:'坚果1',
			price:'2499元起'
		},
		{
			img:"images/images1/hot22.png",
			name:'坚果1',
			price:'2499元起'
		},
		{
			img:"images/images1/hot22.png",
			name:'坚果1',
			price:'2499元起'
		},

	]
]