var theArray=[[{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"1000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"2000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"3000",
	
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"4000",
	
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"5000",
	
	},{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}]
]
var theArray1=[[{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"4000",
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	},{
	img:"images/shouji5.png",
	name:"小米手机6",
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji5.png",
	name:"小米手机6",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	price:"6000",
	tag:"热门"
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	price:"6000",
	tag:"热门"
	}],[{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"4000",
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	},{
	img:"images/shouji5.png",
	name:"小米手机6",
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	}],[{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"4000",
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	},{
	img:"images/shouji5.png",
	name:"小米手机6",
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	}],[{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	},{
	img:"images/shouji3.png",
	name:"小米手机4",
	price:"4000",
	},{
	img:"images/shouji4.png",
	name:"小米手机5",
	},{
	img:"images/shouji5.png",
	name:"小米手机6",
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	},{
	img:"images/shouji.png",
	name:"小米手机1",
	},{
	img:"images/shouji1.png",
	name:"小米手机2",
	},{
	img:"images/shouji2.png",
	name:"小米手机3",
	}]
]
var theArray2=[
	[
		{
			img:'images/zhi2.png',
			p1:'FHD全高清屏 / 人工智能语音系统 ',
			p2:'1599元'
		},
		{
			img:'images/zhi3.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2199元'
		},
		{
			img:'images/zhi4.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2299元'
		},
		{
			img:'images/zhi5.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2399元'
		},
		{
			img:'images/zhi7.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2499元'
		},
		{
			img:'images/zhi8.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2599元'
		},
		{
			img:'images/zhi9.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2699元'
		},
		{
			img1:'images/zhi10.png',
			img2:'images/zhi11.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2799元'
		}
	],
	[
		{
			img:'images/zhi3.png',
			p1:'FHD全高清屏 / 人工智能语音系统 ',
			p2:'1599元'
		},
		{
			img:'images/zhi4.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2199元'
		},
		{
			img:'images/zhi2.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2299元'
		},
		{
			img:'images/zhi8.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2399元'
		},
		{
			img:'images/zhi7.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2499元'
		},
		{
			img:'images/zhi5.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2599元'
		},
		{
			img:'images/zhi9.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2699元'
		},
		{
			img1:'images/zhi10.png',
			img2:'images/zhi11.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2799元'
		}
	],
	[
		{
			img:'images/zhi4.png',
			p1:'FHD全高清屏 / 人工智能语音系统 ',
			p2:'1599元'
		},
		{
			img:'images/zhi3.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2199元'
		},
		{
			img:'images/zhi2.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2299元'
		},
		{
			img:'images/zhi5.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2399元'
		},
		{
			img:'images/zhi8.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2499元'
		},
		{
			img:'images/zhi7.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2599元'
		},
		{
			img:'images/zhi9.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2699元'
		},
		{
			img1:'images/zhi10.png',
			img2:'images/zhi11.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2799元'
		}
	],
	[
		{
			img:'images/zhi2.png',
			p1:'FHD全高清屏 / 人工智能语音系统 ',
			p2:'1599元'
		},
		{
			img:'images/zhi3.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2199元'
		},
		{
			img:'images/zhi4.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2299元'
		},
		{
			img:'images/zhi5.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2399元'
		},
		{
			img:'images/zhi7.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2499元'
		},
		{
			img:'images/zhi8.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2599元'
		},
		{
			img:'images/zhi9.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2699元'
		},
		{
			img1:'images/zhi10.png',
			img2:'images/zhi11.png',
			p1:'变焦双摄，4 轴防抖，骁龙835 处理器 ',
			p2:'2799元'
		}
	]
]
